name: Deploy Rewash+ to GitHub Pages

on:
  push:
    branches:
      - main   # change if your default branch is "master"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o build_output

      # Fix base href automatically
      - name: Fix base href for GitHub Pages
        run: |
          sed -i 's|<base href="/" />|<base href="/RewashPlusDemoApp/" />|' build_output/wwwroot/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_output/wwwroot
          publish_branch: gh-pages
